### ISSUE TITLE
Debugging on modal GPUS

### ISSUE THREAD

**Issue by agokrani** [modal-labs/modal-client#1151]
Hi, 

This is more of a question rather than issue, I am currently trying to run DPOTraining with FSDP on multi gpu and I am having an error that I would like to debug. Is there a way, I could install trl package in editable mode from the fork that I created. How would you guys recommend doing such debugging?

**Comment by thundergolfer** [comment]
Hey @agokrani, thanks for your question. 

You should be able to use `.run_commands("pip install ...")` to install from a Github fork if you first `.apt_install("git")`, because `pip` requires `git` to install repositories. 

Doing this won't provide editable mode though, because of how Modal involves building an image up-front that is used across future containers, and editable mode is used with persistent, mutable local environments to avoid reinstalling on every source code change.

If instead you could reproduce your problem inside a `modal shell`, then you'd have an interactive environment which would support edits to the package source. 

Btw we have a Slack community for questions linked in the top right of the dashboard page :) ([link](https://join.slack.com/t/modallabscommunity/shared_invite/zt-28c8vav1f-9fa5v6XZa3Wx_DrxR9Gk4g))

**Comment by agokrani** [comment]
Hi @thundergolfer, 
Thanks for the response. I need access to gpu for reproducing the error. I guess this won't be possible. Unless there is a way to get access via shell. I am already in the slack community. Thanks for the link again.

**Comment by thundergolfer** [comment]
@agokrani yeah `modal shell` can drop you into a container with the GPU.

**Comment by agokrani** [comment]
Can you tell me how to do this. Like a sample command?

**Comment by thundergolfer** [comment]
It would just be `modal shell main.py` to drop into a shell. Installing from a fork would look like this: https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/stable_diffusion/comfy_ui.py#L69
